language: csharp

sudo: required

env:
    global:
        - BUILD_RELEASE_MONO_VERSION=5.4.0
    matrix:
        - BUILD_CONFIGURATION=Debug
        - BUILD_CONFIGURATION=Release

mono:
    - 5.8.0
    - 5.4.0
    - 5.2.0
    - 5.0.1

addons:
    apt:
        packages:
            - git
            - mono-devel
            - ca-certificates
            # Stuff for building OSX DMGs
            - make
            - sed
            - libplist-utils
            - genisoimage
            # Stuff for building .deb files
            - gzip
            - fakeroot
            - dpkg
            - lintian

# These commands simulate having a graphical display, which is needed
# for our GUI tests.
before_install:
    - "export DISPLAY=:99.0"
    - sh -e /etc/init.d/xvfb start

script:
    - ./build --configuration=$BUILD_CONFIGURATION
    - ./build test+only --configuration=$BUILD_CONFIGURATION --where="cat!=FlakyNetwork"

# We run ~10 builds, but only the one that deploys needs a .app bundle or .deb file
before_deploy:
    - ./build osx
    - ./build deb

deploy:
    # Releases (which are tagged) go to github
    - provider: releases
      skip_cleanup: true
      api_key:
        secure: AjwbRLStNJZb9hAOLfRLK85KlFo2q2Dr1NKCoDS4elek1nqSiOjL1hH0kDgUMx/PJqQVnFU8tbJPL30t9Pj7jcJhp0LhbbPipQE3TCSpafTneSEbdz5HT+OdghWCZhUhfs07wGNTFUwcAO4WBZ7wv1AnfdfogHdA5RMdykiIl38=
      file_glob: true
      file:
        - _build/repack/$BUILD_CONFIGURATION/ckan.exe
        - _build/osx/CKAN.dmg
        - _build/deb/ckan_*.deb
        - _build/out/AutoUpdater/$BUILD_CONFIGURATION/bin/AutoUpdater.exe
      on:
        repo: KSP-CKAN/CKAN
        tags: true
        condition: $BUILD_CONFIGURATION = Release && $(mono --version | perl -ne'/version (\d+\.\d+\.\d+)/ and print $1') = $BUILD_RELEASE_MONO_VERSION
        # all_branches needed as a workaround for travis-ci#1675
        all_branches: true

    # Any merge to master gets sent to
    # http://ckan-travis.s3-website-us-east-1.amazonaws.com/
    - provider: s3
      skip_cleanup: true
      access_key_id: AKIAI5JWAEFPFK6GH3XA
      secret_access_key:
        secure: b0PPlD7auqysK2LHA8N1US03dE/VKH2rOTwIqpIh50l/gURuXEl7Nd8S7qlf2dpEmz+8D5pIWD+J9scfrdD8Uuakhi3sQbqcV26UiR6+Ye06eGQfmIzqzAECt2naqEy7VJ/xrqq5aaaf8QhcOQMba3qVvwDSzkB2fJeh7+D6EY8=
      bucket: ckan-travis
      acl: public_read
      local_dir: _build/repack/$BUILD_CONFIGURATION
      on:
        repo: KSP-CKAN/CKAN
        branch: master
        condition: $BUILD_CONFIGURATION = Release && $(mono --version | perl -ne'/version (\d+\.\d+\.\d+)/ and print $1') = $BUILD_RELEASE_MONO_VERSION

notifications:
  irc:
    channels:
      - "irc.esper.net#ckan-ci"
    template:
      - "%{repository_name}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
